# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  labels:
    app: app
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer   # ⭐ Yeh line add ki gayi hai
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app
    release: {{ .Release.Name }}

